### ISSUE TITLE
2.3.11 Symbol not found 

### ISSUE THREAD

**Issue by Said13** [AssistoLab/DropDown#207]
After updating pod to 2.3.11 I got an error 

`dyld: Symbol not found: _$S8DropDown0aB4CellC15normalTextColorSo7UIColorCSgvg
  Referenced from: /var/containers/Bundle/Application/DDDD96FA-0A7A-49EA-B51A-EB7791855620/*******.app/*******
  Expected in: /private/var/containers/Bundle/Application/DDDD96FA-0A7A-49EA-B51A-EB7791855620/*******.app/Frameworks/DropDown.framework/DropDown
 in /var/containers/Bundle/Application/DDDD96FA-0A7A-49EA-B51A-EB7791855620/*******.app/*******`

**Comment by kevin-hirsch** [comment]
Hello @Said13 👋

What version of Swift are you using? And which version of Xcode?
If you are using Swift 4 or 4.1, you must use maximum version **2.3.2**

Otherwise, did you try deleting "Pods" folder completely and do `pod install` again.
If still not working, try "Clean Build Folder" from Xcode menu 😉
